---
name: upload release to PyPI
"on":
  release:
    types:
      - published

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Configure PyPI token
        run: poetry config pypi-token.pypi ${{ secrets.PYPI_API_KEY }}
      - name: Publish package
        run: poetry publish --build
